apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: WebSphere-Liberty-template
  title: WebSphere Liberty with ArgoCD and OC build config
  description: Create a simple WebSphere Liberty app with ArgoCD and OC build config
  tags:
    - recommended
    - java
    - websphere-liberty
    - maven
    - cicd
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Provide Information for Application
      required:
        - component_id
      properties:
        component_id:
          title: Name
          type: string
          description: Repo name
          default: my-liberty-app
          ui:field: EntityNamePicker
          maxLength: 23
        image_name:
          title: Image name
          type: string
          default: mylibertyapp
          description: Image Name
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
          default: A cool websphere liberty app
    - title: Provide Image Registry Information
      required:
        - image_registry
      properties:
        image_registry:
          title: Image Registry
          type: string
          enum:
            - OpenShift Build Config
            - Github Action
            - Tekton Pipeline
    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: github.com
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: ocp-rhdh-poc

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: "https://github.com/mattbman23/wasAppMod"

    - id: publish
      name: Publish
      action: publish:github
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.component_id}}"
        repoVisibility: public

    - id: generate
      name: Generate OpenShift BuildConfig
      action: fetch:template
      input:
        url: "https://github.com/mattbman23/backstage_k8_deployment_template/blob/main/buildconfig.yml"
        values:
          repoUrl: "https://${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{parameters.component_id}}"
          imageName: ${{ parameters.image_name  }}

    - id: apply-buildconfig
      name: Apply OpenShift BuildConfig
      action: kubernetes:apply
      input:
        manifests:
          - ${{ steps.generate.output.manifests }}
