apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: WebSphere-Liberty-template
  title: WebSphere Liberty with ArgoCD and OC build config
  description: Create a simple WebSphere Liberty app with ArgoCD and OC build config
  tags:
    - recommended
    - java
    - websphere-liberty
    - maven
    - cicd
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Provide Information for Application
      required:
        - component_id
        - java_package_name
      properties:
        component_id:
          title: Name
          type: string
          description: Repo name
          default: my-liberty-app
          ui:field: EntityNamePicker
          maxLength: 23
        group_id:
          title: Group Id
          type: string
          default: redhat.janus
          description: Maven Group Id
        artifact_id:
          title: Artifact Id
          type: string
          default: liberty-app
          description: Maven Artifact Id
        java_package_name:
          title: Java Package Name
          default: org.redhat.janus
          type: string
          description: Name for the java package. eg (com.redhat.blah)
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
          default: A cool websphere liberty app
    - title: Provide Image Registry Information
      required:
        - image_registry
      properties:
        image_registry:
          title: Image Registry
          type: string
          enum:
            - Openshift
            - Quay
      dependencies:
        image_registry:
          oneOf:
            - properties:
                image_registry:
                  enum:
                    - Openshift
                image_host:
                  title: Image Host
                  type: string
                  description: Host for storing image
                  default: image-registry.openshift-image-registry.svc:5000
                image_tag:
                  title: Image Tag
                  default: latest
                  type: string
                  description: Build Image tag
            - properties:
                image_registry:
                  enum:
                    - Quay
                image_host:
                  title: Image Host
                  type: string
                  description: Host for storing image
                  default: quay-4z2t2.apps.67c1045bd8856f9bb04f2985.am1.techzone.ibm.com
                image_organization:
                  title: Organization
                  type: string
                  description: Name of the Quay Organization
                  default: quayadmin
                image_tag:
                  title: Image Tag
                  default: latest
                  type: string
                  description: Build Image tag
    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: github.com
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: ocp-rhdh-poc

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: "https://github.com/mattbman23/wasAppMod"

    - id: publish
      name: Publish
      action: publish:github
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.component_id}}"
        repoVisibility: public

    - id: generate # oc build
      name: Generate OpenShift BuildConfig
      action: fetch:template
      input:
        url: "https://github.com/mattbman23/backstage_k8_deployment_template/blob/main/buildconfig.yml"
        values:
          repoUrl: "${{ parameters.repo.host }}/${{ parameters.repo.owner }}/${{parameters.component_id}}"
          imageName: ${{  }}

    - id: apply-buildconfig
      name: Apply OpenShift BuildConfig
      action: kubernetes:apply
      input:
        manifests:
          - ${{ steps.generate.output.manifests }}
